const MyProjects = [
  {
    title: "قیمت انلاین تجهیزات تیراندازی",
    technologies: [
      "Html & Css",
      "Bootstrap",
      "Responsive Design",
      "JavaScript",
      "tgju Api",
    ],
    cover: process.env.PUBLIC_URL + "/images/price-guns.png",
    link: "https://mohammadebrahimzadeh.github.io/PriceGuns_v-online/",
    Completed: true,
    ClassNames: "price-guns",
  },
  {
    title: "وب سایت شرکتی کاسوکا",
    technologies: [
      "Html & Css",
      "Sass",
      "Responsive Design",
      "React.Js Modular",
    ],
    cover: process.env.PUBLIC_URL + "/images/kasuka.png",
    link: "https://mohammadebrahimzadeh.github.io/kasuka/",
    Completed: true,
    ClassNames: "kasuka",
  },
  {
    title: "صرافی انلاین تریدمن",
    technologies: [
      "Html & Css",
      "Sass",
      "Responsive Design",
      "React.Js Modular",
      "SPA Page",
      "Tradingview Widget",
    ],
    cover: process.env.PUBLIC_URL + "/images/trademan.png",
    link: "https://mohammadebrahimzadeh.github.io/tradeMan/",
    Completed: true,
    ClassNames: "trademan",
  },
  {
    title: "im250db سایت فیلم و سریال ",
    technologies: [
      "Html & Css",
      "Sass",
      "Responsive Design",
      "React.Js Modular",
      "SPA Page",
      "API imdb",
      "Iran Sans Font",
    ],
    cover: process.env.PUBLIC_URL + "/images/im250db.png",
    link: "https://mohammadebrahimzadeh.github.io/im250db/",
    Completed: true,
    ClassNames: "im250db",
  },
  {
    title: "برنامه هواشناسی",
    technologies: [
      "Html & Css",
      "Sass",
      "Responsive Design",
      "openweather api",
    ],
    cover: process.env.PUBLIC_URL + "/images/weather.png",
    link: "https://mohammadebrahimzadeh.github.io/weather/",
    Completed: true,
    ClassNames: "weather",
  },
  {
    title: "نرم افزار بادخوانی",
    technologies: [
      "Html & Css",
      "Sass",
      "Responsive Design",
      "SPA Page",
      "شبیه ساز واقعی تیراندازی",
    ],
    cover: process.env.PUBLIC_URL + "/images/targetFire.png",
    link: "https://mohammadebrahimzadeh.github.io/trgetFire/",
    Completed: true,
    ClassNames: "targetFire",
  },
  {
    title: "دیجیکالا",
    technologies: [
      "Html & Css",
      "Sass",
      "Responsive Design",
      "React.Js Modular",
      "SPA Page",
      "Digikala APi",
      "BackEnd",
    ],
    cover: process.env.PUBLIC_URL + "/images/Digikala.png",
    link: "https://mohammadebrahimzadeh.github.io/digikala/",
    Completed: false,
    ClassNames: "Digikala",
  },
  {
    title: "بیمه دی",
    technologies: [
      "Html & Css",
      "Sass",
      "Responsive Design",
      "React.Js Modular",
      "SPA Page",
    ],
    cover: "/images/Insurance-dey.png",
    link: "https://insurance-dey.pages.dev/",
    Completed: true,
    ClassNames: "Insurance-dey",
  },
];
export default MyProjects;
