const MyProjects = [
  {
    title: "پخش فیلم",
    technologies: ["Html & Css", "Bootstrap", "Responsive Design"],
    cover: process.env.PUBLIC_URL + "/images/play-film-for-student.png",
    link: "https://play-film-for-student.vercel.app/",
    Completed: true,
    ClassNames: "play-film-for-student",
  },
  {
    title: "قیمت انلاین تجهیزات تیراندازی",
    technologies: ["Html & Css", "Bootstrap", "Responsive Design", "JavaScript", "tgju Api"],
    cover: process.env.PUBLIC_URL + "/images/price-guns.png",
    link: "https://price-guns-v-online.vercel.app/",
    Completed: true,
    ClassNames: "price-guns",
  },
  {
    title: "وب سایت شرکتی کاسوکا",
    technologies: ["Html & Css", "Sass", "Responsive Design", "React.Js Modular"],
    cover: process.env.PUBLIC_URL + "/images/kasuka.png",
    link: "https://mohammadebrahimzadeh.github.io/kasuka/",
    Completed: true,
    ClassNames: "kasuka",
  },
  {
    title: "صرافی انلاین تریدمن",
    technologies: ["Html & Css", "Sass", "Responsive Design", "React.Js Modular", "SPA Page", "Tradingview Widget"],
    cover: process.env.PUBLIC_URL + "/images/trademan.png",
    link: "https://mohammadebrahimzadeh.github.io/tradeMan/",
    Completed: true,
    ClassNames: "trademan",
  },
  {
    title: "im250db سایت فیلم و سریال ",
    technologies: ["Html & Css", "Sass", "Responsive Design", "React.Js Modular", "SPA Page", "API imdb", "Iran Sans Font"],
    cover: process.env.PUBLIC_URL + "/images/im250db.png",
    link: "https://mohammadebrahimzadeh.github.io/im250db/",
    Completed: true,
    ClassNames: "im250db",
  },
  {
    title: "نرم افزار بادخوانی",
    technologies: ["Html & Css", "Sass", "Responsive Design", "SPA Page", "شبیه ساز واقعی تیراندازی"],
    cover: process.env.PUBLIC_URL + "/images/targetFire.png",
    link: "https://target-fire.vercel.app/",
    Completed: true,
    ClassNames: "targetFire",
  },
  {
    title: "دیجیکالا",
    technologies: ["Html & Css", "Sass", "Responsive Design", "React.Js Modular", "SPA Page", "Digikala APi", "BackEnd"],
    cover: process.env.PUBLIC_URL + "/images/Digikala.png",
    link: "https://digikala-k2.vercel.app/",
    Completed: false,
    ClassNames: "Digikala",
  },
  {
    title: "بیمه دی",
    technologies: ["Html & Css", "Sass", "Responsive Design", "React.Js Modular", "SPA Page"],
    cover: "/images/Insurance-dey.png",
    link: "https://insurance-dey.vercel.app/",
    Completed: true,
    ClassNames: "Insurance-dey",
  },
];
export default MyProjects;
